CREATE TABLE `bookmark`.`USERS` (
	`NICKNAME` varchar(25) NOT NULL,
	`EMAIL` varchar(45) NOT NULL,
    `PASSWORD` varchar(1024) NOT NULL,
    `ENABLED` TINYINT(1) NOT NULL,
    PRIMARY KEY(`EMAIL`),
    UNIQUE KEY uni_email (`EMAIL`)
)Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `bookmark`.`USER_ROLES` (
	`USER_ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
    `EMAIL` varchar(45) NOT NULL,
    `ROLE` varchar(45) NOT NULL,
    PRIMARY KEY(`USER_ROLE_ID`),
    UNIQUE KEY uni_email_role (`ROLE`, `EMAIL`),
    KEY fk_email_idx(`EMAIL`),
    CONSTRAINT fk_email FOREIGN KEY (`EMAIL`) REFERENCES `bookmark`.`USERS`(`EMAIL`)
)Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `bookmark`.`PERSISTENT_LOGINS` (
	`USERNAME` varchar(64) not null,
    `SERIES` varchar(64) not null,
    `TOKEN` varchar(64) not null,
    `LAST_USED` timestamp not null,
    PRIMARY KEY (`SERIES`)
)Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `bookmark`.`FOLDER` (
	`FOLDER_ID` int(10) NOT NULL AUTO_INCREMENT,
    `NAME` varchar(45) NOT NULL,
    `PARENT_ID` int(10),
    `USERNAME` varchar(64) NOT NULL,
	PRIMARY KEY(`FOLDER_ID`),
	CONSTRAINT `fk_parent_id` FOREIGN KEY(`PARENT_ID`) REFERENCES `FOLDER`(`FOLDER_ID`),
    CONSTRAINT `fk_username` FOREIGN KEY(`USERNAME`) REFERENCES `USERS`(`EMAIL`)
) Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `bookmark`.`BOOKMARK` (
	`BOOKMARK_ID` int(10) NOT NULL AUTO_INCREMENT,
    `DESCRIPTION` varchar(200) NOT NULL,
    `URL` varchar(1024) NOT NULL,
    `FOLDER_ID` int(10) NOT NULL,    
    PRIMARY KEY(`BOOKMARK_ID`),
    CONSTRAINT fk_folder_id FOREIGN KEY(`FOLDER_ID`) REFERENCES `FOLDER`(`FOLDER_ID`)
)Engine=InnoDB DEFAULT CHARSET=utf8;