CREATE TABLE USERS (
    NICKNAME varchar(25) NOT NULL,
    EMAIL varchar(45) NOT NULL,
    PASSWORD varchar(1024) NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    PRIMARY KEY(EMAIL),
    UNIQUE (EMAIL)
);

CREATE TABLE USER_ROLES (
    USER_ROLE_ID serial NOT NULL,
    EMAIL varchar(45) NOT NULL,
    ROLE varchar(45) NOT NULL,
    PRIMARY KEY(USER_ROLE_ID),
    UNIQUE (ROLE, EMAIL),    
    FOREIGN KEY (EMAIL) REFERENCES USERS(EMAIL)
);

CREATE TABLE PERSISTENT_LOGINS (
    USERNAME varchar(64) not null,
    SERIES varchar(64) not null,
    TOKEN varchar(64) not null,
    LAST_USED timestamp not null,
    PRIMARY KEY (SERIES)
);

CREATE TABLE FOLDER (
    FOLDER_ID serial NOT NULL,
    NAME varchar(45) NOT NULL,
    PARENT_ID int,
    USERNAME varchar(64) NOT NULL,
    PRIMARY KEY(FOLDER_ID),
    FOREIGN KEY(PARENT_ID) REFERENCES FOLDER(FOLDER_ID),
    FOREIGN KEY(USERNAME) REFERENCES USERS(EMAIL)
);

CREATE TABLE BOOKMARK (
    BOOKMARK_ID serial NOT NULL,
    DESCRIPTION varchar(200) NOT NULL,
    URL varchar(1024) NOT NULL,
    FOLDER_ID int NOT NULL,    
    PRIMARY KEY(BOOKMARK_ID),
    FOREIGN KEY(FOLDER_ID) REFERENCES FOLDER(FOLDER_ID)
);